### ISSUE TITLE
如何启用gpu？

### ISSUE THREAD

**Issue by lyc-python** [ZzzzzZXxxX/yolo3_keras_Logo_Detection#2]
您好，我在尝试使用自己数据进行训练时，发现耗时过长。我看有用到kreas和TensorFlow，如何启用GPU加速？

**Comment by ZzzzzZXxxX** [comment]
我这个里面默认就是开gpu的，前提是你安装了gpu版的tensorflow



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyc-python <notifications@github.com&gt;
发送时间: 2019年10月30日 16:01
收件人: ZzzzzZXxxX/yolo3_keras_Logo_Detection <yolo3_keras_Logo_Detection@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ZzzzzZXxxX/yolo3_keras_Logo_Detection] 如何启用gpu？ (#2)




您好，我在尝试使用自己数据进行训练时，发现耗时过长。我看有用到kreas和TensorFlow，如何启用GPU加速？

**Comment by lyc-python** [comment]
调试好了，是我的环境问题，谢谢
