### ISSUE TITLE
求更多代码注释

### ISSUE THREAD

**Issue by zhangwujun666** [ZzzzzZXxxX/yolo3_keras_Logo_Detection#6]
开发者你好，我在做一个实验课题，需求和你这个项目比较符合。正在学习CNN和YOLO相关知识，我很想用本项目作为学习材料和研究目标，可否提供下本项目的相关参考资料？谢谢你啦

**Comment by ZzzzzZXxxX** [comment]
不好意思，由于时间久远，相关的都在README中提供。你可以参考本项目以及我的另外一个旗帜识别的项目，使用yolov4模型进行研究



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: John zhang <notifications@github.com&gt;
发送时间: 2020年7月22日 01:21
收件人: ZzzzzZXxxX/yolo3_keras_Logo_Detection <yolo3_keras_Logo_Detection@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ZzzzzZXxxX/yolo3_keras_Logo_Detection] 求更多代码注释 (#6)





 
开发者你好，我在做一个实验课题，需求和你这个项目比较符合。正在学习CNN和YOLO相关知识，我很想用本项目作为学习材料和研究目标，可否提供下本项目的相关参考资料？谢谢你啦

**Comment by zhangwujun666** [comment]
好的，感谢！
